# Generated by Django 4.0.1 on 2022-01-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutcat_born_alter_aboutcat_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcat',
            name='name_en',
            field=models.CharField(default='', max_length=255, verbose_name='名前(英語)'),
        ),
    ]
